version: 2.1
orbs:
  node: circleci/node@10
jobs:
  test-and-build:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-depsendencies-{{ checksum "package.json" }}
      - run: yarn test
      - run: yarn build
workflows:
  test-and-build:
    jobs:
      - test-and-build
