export { default as Error } from "./Error";
export { default as Footer } from "./Footer";
export { default as Form } from "./Form";
export { default as GlobalCSS } from "./GlobalCSS";
export { default as Header } from "./Header";
export { default as Partners } from "./Partners";
export { default as SocialMedia } from "./SocialMedia";
export { default as ThankYou } from "./ThankYou";
export { default as Video } from "./Video";
